#!/usr/bin/env lua

function trim(s) 
  if s then
    return s:gsub("^%s+", ""):gsub("%s+$", "")
  else 
    return s
end end

function items (t)
  local i,n = 0, #t 
  return function ()
    i = i + 1
    if i <= n then return t[i] end
end end 

-- for item in items{1,2,3,4}  do print(item) end
               
function paras (src) 
  if src then io.input(src) end
  return function ()
    local line, p = trim(io.read()), {}
    while line do   
      if    line == ""  
      then  return p 
      else  p[#p+1] = line
      end 
      if line == "" then p = {} end
      line = trim(io.read())
    end
    if #p > 0 then return p end
    return nil
  end   
end
 
for para in paras(arg[1]) do
  print("")
  print(table.concat(para," .... ")) 
end 