#!/usr/bin/env lua

require "lib"
   
function ako(       
function paras () 
  io.input(arg[1] or nil) 
  return function ()
    local s, p = trim(io.read()), {}
    while s do   
      if s~="" then p[#p+1] = s end 
      if s=="" then return p    end
      if s=="" then p = {}      end
      s = trim(io.read())
    end
    if #p > 0 then return p end
    return nil
end end
 
for para in paras() do
  print("")
  print(table.concat(para," .... ")) 
end 